let a = 10
let b = 2
let c 

try {

    console.log("Soma: ", a + c)

} catch (erro) {

    console.log.apply("Erro: ", error)
    
}